#!/bin/bash

NAME="jennylouthan"
FLASKDIR=/Users/jenniferlouthan/Projects/Web/jennylouthan/app
VENVDIR=/Users/jenniferlouthan/Projects/Web/jennylouthan/env
SOCKFILE=/Users/jenniferlouthan/Projects/Web/jennylouthan/sock
NUM_WORKERS=3

echo "Starting $NAME"

# activate the virtualenv
cd $VENVDIR
source bin/activate

export PYTHONPATH=$FLASKDIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your unicorn
exec gunicorn app:app -b 127.0.0.1:4141 \
  --name $NAME \
  --workers $NUM_WORKERS \
  --log-level=debug \
  --bind=unix:$SOCKFILE
